#!/usr/bin/env python3
import pathlib
from os import listdir, PathLike
from os.path import isfile, join, isdir

__TARGET_DIR = 'content'

_TARGET_DIR= pathlib.Path(__file__).parent.joinpath(__TARGET_DIR)


GHEAD = """
  <head>
    <!--
        If for some reason you are reading the code and insulting me for this trash,
        just keep in mind I made this on saturday night while drinking beer and studing
        statistics. Peace ^.^ @takenX10
    -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{fname}</title>
    <style>
      :root {
        --b: #fbf1c7;
        --b2: #bdae93;
        --f: #282828;
        --d: #d65d0e;
      }

      @media (prefers-color-scheme: dark) {
        :root {
          --b: #282828;
          --b2: #7c6f64;
          --f: #fbf1c7;
          --d: #fe8019;
        }
      }

      @media (max-width: 880px) {
        body {
          line-height: 1.5rem;
        }

        a {
          width: 100vw !important;
        }

        .anno > a {
          width: 100%;
          margin: 0.5rem !important;
          padding: 1rem !important;
        }
      }

      body {
        color: var(--f);
        background: var(--b);
        font-size: 16px;
        text-align: center;
        font-family: monospace;
        margin: 0;
      }

      h1 {
        padding-top: 5vh;
        font-size: 42px;
      }

      hr {
        width: 100%;
      }

      b {
        color: var(--d);
      }

      a {
        color: inherit;
        transition: 0.2s;
      }

      a:hover {
        scale: 1.05;
        background-color: var(--d);
        color: var(--f) !important;
      }

      .disclaimer {
        background-color: var(--b2);
        margin: 2%;
        padding: 1%;
        width: fit-content;
      }

      .link-utili > a {
        color: var(--d);
        margin: 0 1%;
      }

      .anno {
        margin: 2%;
        display: flex;
        flex-wrap: wrap;
      }

      .anno > h2 {
        text-align: left;
        width: 100%;
      }

      .anno > a {
        margin: 1%;
        width: fit-content;
        color: var(--f);
        padding: 1%;
        border: solid 2px;
        text-decoration: none;
      }

      a.wip {
        color: var(--f);
        pointer-events: none;
        border: 0px;
        text-decoration: none;
      }
    </style>
  </head>
"""

body_start = """
<body>
<h1>Index of <a href="https://csunibo.github.io/">csunibo</a>/<a href="{furl}/">{fname}</a>/</h1><hr><div class="g">
<a href="https://csunibo.github.io/algoritmi-e-strutture-di-dati/esercizi" class="d">esercizi</a><p>20 Jun 22 14:21 UTC</p><p>4.1 kB</p>
<a href="https://csunibo.github.io/algoritmi-e-strutture-di-dati/libri" class="d">libri</a><p>20 Jun 22 14:21 UTC</p><p>4.1 kB</p><a href="https://csunibo.github.io/algoritmi-e-strutture-di-dati/lucidi" class="d">lucidi</a><p>20 Jun 22 14:21 UTC</p><p>4.1 kB</p><a href="https://csunibo.github.io/algoritmi-e-strutture-di-dati/prove" class="d">prove</a><p>20 Jun 22 14:21 UTC</p><p>4.1 kB</p><a href="https://csunibo.github.io/algoritmi-e-strutture-di-dati/README.pdf">README.pdf</a><p>20 Jun 22 14:21 UTC</p><p>94 kB</p></div><hr><p>Generated by <a href="https://github.com/lucat1/statik">statik</a> on 20 Jun 22 14:22 UTC</p></body>
"""



def _get_fpath_from_root(fl):
  return str(fl).split('matunibo.github.io')

def _gen_suburl(fl) -> str:
  return _BASE_URL + _get_fpath_from_root(fl)


def _gen_index(spath) -> str:
  index_el = """
    <a href="{sub_url}" class="{dclass}">sub_name</a><p>{sub_tchange}</p><p>{sub_size}</p>
  """
  for fl in listdir(spath):
    cdict = {}
    if isdir(fl): cdict['dclass'] = 'd'
    cdict['sub_url'] = _gen_suburl(spath.joinpath(fl))






def recursive_gen_index(path:[PathLike, str]) -> None:
  _gen_index(path)
  for fl in listdir(path):
    if isdir(fl):
      recursive_gen_index(path.joinpath(fl))
  return None

if __name__ == "__main__":
  recursive_gen_index(_TARGET_DIR)
